---
title: "Jovany Cota"
---

# **<u>Education</u>**
### **University of California, Santa Barbara**
- *B.A. in Geography with a GIS Emphasis - GPA: 3.23 (June 2022)*
- **Relevant Coursework** : Remote Sensing of the Environment (series: 1-3), Geographical Data Analysis, Intro to GIS, Technical Issues in GIS, GIS Design and Applications, Cartographic Design and Geovisualization, Maps & Spatial Reasoning

# **<u>Experience</u>**
### **Apple Via TEKsystems (Los Angeles, CA)**
#### *Data Quality Assurance Lead (December 2024 - Present)*
- Delegate daily tasks and goals to a 40 person team while ensuring project milestones are being met.
- Coordinate with different teams located in other parts of the world to find any areas open for improvement and strengths the team can build on.
- Produce standard operating procedures for projects that can be used by various teams and be applied to future projects.
- Filter and sort through large sets of daily captured data before it is sent to the next team of engineers.
- Operate unreleased hardware/software technology and troubleshoot any new issues that have never been experienced.


### **ID Plans (Tampa, FL)**
#### *Field Data Specialist (September 2023 - December 2024)* 
- Develop detailed maps for commercial, tenant, and retail properties, highlighting utilities and all onsite amenities, tailored for property management solutions.
- Ensure meticulous attention to detail and accuracy in all aspects of data collection, surveying, and entry, adhering closely to client-specific instructions to maintain the quality and credibility of site survey property inspection plans.
- Utilize technical proficiency in the daily operation of laser measuring tools, 3D cameras, aerial maps, and specialized software for efficient data entry, surveyor mapping, and comprehensive reporting.
- Demonstrate exceptional organizational and time management skills to meet project deadlines effectively. Prioritize tasks and execute them efficiently, following instructions meticulously to achieve project goals with minimal oversight.
- Flexibly navigate changing circumstances in commercial property inspection settings, finding innovative solutions to ensure project success.

### **Apple Maps Via RMSI North America Inc.	(Sunnyvale, CA)**
#### *GIS Technician (June 2022 - September 2023)*
- Conducted meticulous 3D terrain and land cover edits to align with real-world data, addressing user-reported inconsistencies effectively.
- Crafted user-friendly 2D/3D maps using advanced GIS software and methodologies, enhancing accessibility for Apple Maps users.
- Directed the development of 3D landmark models, overseeing all stages from conceptualization to final production, ensuring accuracy and quality.
- Analyzed and rectified mapping irregularities within extensive JSON/Python datasets, ensuring data integrity and accuracy.

### **UCSB Movement Data Science Lab (Santa Barbara, CA)**
#### *Research Assistant	(October 2020 – April 2022)*
- Investigate the dynamics of human mobility in wildfire-affected regions midst the COVID-19 Pandemic, contributing to pioneering research efforts.
- Employ advanced statistical and spatial analysis techniques to dissect extensive data sets to unveil nuanced insights.
- Craft and curate a repository of maps, plots, and visual aids, ensuring effective dissemination of research outcomes to diverse stakeholders.
- Utilize GIS software to execute sophisticated statistical analysis, pinpointing anomalies and trends within the collected data for comprehensive understanding.

## **<u>Skills</u>**
- Advanced in Rstudio, ArcGis, Python, QGIS
- Spatial Data Analysis
- Data Collection & Database Management 
- Data Visualization
- Cartography & Geovisualization
- Remote sensing
- Project management & communication
